# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 103acf22bd307f26b17982061b5b708eb0fd04d62e4175eb524872aff6b6339bee024684592f827ecceeacfa026cab65b723df3124704bfaabc80b207f46823f

test:
  secret_key_base: 82603d2eb18f2b0b782a25b990e77250f51086c3e8b4fd80d4b6fcc261c197ccc7cd4de5050653aa55cf6722e8782ec42233e76eafe5f1eb271e102e014fa7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
